### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [townboyy/C202309#4]
### 없는 파일
- challenge/week4/pyramidReverse.c
- challenge/week6/studentGrade.c
- practice/week7/7_travel.c
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/do-while_even
    - Warning: more '%' conversions than data arguments [line 9]
        - 해당 라인에 서식지정자 수와 변수 수를 확인해주세요.

**Comment by townboyy** [comment]
challenge/week4/pyramidReverse.c 의 위치를 변경하였고
challenge/week6/studentGrade.c 와 practice/week7/7_travel.c 의 이름을 변경하였으며
 challenge/week3/do-while_even 에서 서식 지정사 수가 두 개여서 하나를 제거하였고
i++을 추가하여 홀수만 출력되도록 코드를 제대로 수정하였습니다
